//
//  LLMProviderProtocol.swift
//  llmHub
//
//  Created by AI Assistant on 11/27/25.
//

import Foundation

/// Protocol defining the interface for an LLM (Large Language Model) provider.
@MainActor
protocol LLMProvider: Identifiable {
    /// The unique identifier of the provider.
    var id: String { get }
    /// The display name of the provider.
    var name: String { get }
    /// The API endpoint URL for the provider.
    var endpoint: URL { get }
    /// Indicates if the provider supports streaming responses.
    var supportsStreaming: Bool { get }
    /// The list of available models from this provider.
    var availableModels: [LLMModel] { get }
    /// The default HTTP headers to be included in requests.
    var defaultHeaders: [String: String] { get }
    /// Pricing information for the provider.
    var pricing: PricingMetadata { get }
    /// Indicates if the provider is correctly configured (e.g., has an API key).
    var isConfigured: Bool { get }

    /// Fetches the list of available models from the provider.
    /// - Returns: An array of `LLMModel` objects.
    func fetchModels() async throws -> [LLMModel]

    /// Builds a URLRequest for a chat completion.
    /// - Parameters:
    ///   - messages: The history of messages in the chat session.
    ///   - model: The model identifier to use.
    /// - Returns: A configured `URLRequest`.
    func buildRequest(messages: [ChatMessage], model: String) throws -> URLRequest

    /// Builds a URLRequest for a chat completion with tool support.
    /// - Parameters:
    ///   - messages: The history of messages in the chat session.
    ///   - model: The model identifier to use.
    ///   - tools: The list of tools available to the model.
    /// - Returns: A configured `URLRequest`.
    func buildRequest(messages: [ChatMessage], model: String, tools: [ToolDefinition]?) throws -> URLRequest

    /// Streams the response from the provider.
    /// - Parameter request: The request to execute.
    /// - Returns: An async throwing stream of `ProviderEvent`s.
    func streamResponse(from request: URLRequest) -> AsyncThrowingStream<ProviderEvent, Error>

    /// Parses token usage from the provider's response data.
    /// - Parameter response: The raw response data.
    /// - Returns: A `TokenUsage` object if parsing is successful, otherwise nil.
    func parseTokenUsage(from response: Data) throws -> TokenUsage?
}

/// Tool definition for LLM function calling.
struct ToolDefinition: Sendable {
    /// The name of the tool.
    let name: String
    /// A description of what the tool does.
    let description: String
    /// The JSON schema for the tool's input arguments.
    let inputSchema: [String: Any]
    
    /// Initializes a `ToolDefinition` from a generic tool.
    /// - Parameter tool: The tool to define.
    init(from tool: any Tool) {
        self.name = tool.name
        self.description = tool.description
        self.inputSchema = tool.inputSchema
    }
}

// Default implementation for providers that don't support tools yet
extension LLMProvider {
    /// Default implementation that ignores tools and calls the basic `buildRequest`.
    func buildRequest(messages: [ChatMessage], model: String, tools: [ToolDefinition]?) throws -> URLRequest {
        // Default: ignore tools, just build regular request
        try buildRequest(messages: messages, model: model)
    }
}

/// Represents a specific LLM model.
struct LLMModel: Identifiable, Hashable, Sendable {
    /// The unique identifier of the model.
    let id: String
    /// The display name of the model.
    let displayName: String
    /// The context window size in tokens.
    let contextWindow: Int
    /// Indicates if the model supports tool use/function calling.
    let supportsToolUse: Bool
    /// The maximum number of output tokens.
    let maxOutputTokens: Int
}

extension LLMModel {
    /// Initializes a new `LLMModel`.
    /// - Parameters:
    ///   - id: The unique identifier.
    ///   - name: The display name.
    ///   - maxOutputTokens: The maximum output tokens.
    ///   - contextWindow: The context window size (default: 128,000).
    ///   - supportsToolUse: Whether tool use is supported (default: true).
    init(id: String, name: String, maxOutputTokens: Int, contextWindow: Int = 128_000, supportsToolUse: Bool = true) {
        self.id = id
        self.displayName = name
        self.contextWindow = contextWindow
        self.supportsToolUse = supportsToolUse
        self.maxOutputTokens = maxOutputTokens
    }
}

/// Pricing metadata for an LLM provider.
struct PricingMetadata: Sendable {
    /// Cost per 1,000 input tokens in USD.
    var inputPer1KUSD: Decimal
    /// Cost per 1,000 output tokens in USD.
    var outputPer1KUSD: Decimal
    /// The currency code (e.g., "USD").
    var currency: String
}

/// Events emitted during an LLM response stream.
enum ProviderEvent: Sendable {
    /// A text token generated by the model.
    case token(text: String)
    /// A thinking process update (for reasoning models).
    case thinking(String) // Add this back
    /// A request to use a tool.
    case toolUse(id: String, name: String, input: String)
    /// The completion of the message generation.
    case completion(message: ChatMessage)
    /// Token usage statistics for the response.
    case usage(TokenUsage)
    /// A reference ID for the interaction.
    case reference(String)
    /// An error that occurred during streaming.
    case error(LLMProviderError)
}

/// Errors specific to LLM providers.
enum LLMProviderError: LocalizedError, Sendable {
    /// The request payload was invalid.
    case invalidRequest
    /// The API key or authentication is missing.
    case authenticationMissing
    /// The rate limit was exceeded.
    case rateLimited(retryAfter: TimeInterval?)
    /// Failed to decode the response.
    case decodingFailed
    /// The server returned an error.
    case server(reason: String)
    /// A network error occurred.
    case network(URLError)

    /// A localized description of the error.
    var errorDescription: String? {
        switch self {
        case .invalidRequest: "Invalid request payload."
        case .authenticationMissing: "Missing API key for provider."
        case .rateLimited(let retryAfter): "Rate limited. Retry after: \(retryAfter?.description ?? "unknown")."
        case .decodingFailed: "Failed to decode provider response."
        case .server(let reason): "Provider error: \(reason)"
        case .network(let error): "Network error: \(error.localizedDescription)"
        }
    }
}
